<?php

namespace FahrzeugdatenblattBundle\Repository;

/**
 * FahrzeugdatenblattRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FahrzeugdatenblattRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	 * @return mixed
	 */
	public function findByMarke($markenname)
	{
		return $this->createQueryBuilder('fahrzeugdatenblatt')
			->andWhere('fahrzeugdatenblatt.fahrzeugMarke = :name')
			->setParameter('name',$markenname)
			->getQuery()
			->getOneOrNullResult();
	}

	/**
	 * @return mixed
	 */
	public function countAllCars()
	{
		$alleKarren = $this->createQueryBuilder('fahrzeugdatenblatt')
			->getQuery()
			->getArrayResult();
		$counted = count($alleKarren);
		return $counted;
	}
}
