<?php

namespace FahrzeugdatenblattBundle\Repository;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * FahrzeugdatenblattRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FahrzeugdatenblattRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	 * @return mixed
	 */
	public function findByMarke($markenname)
	{
		return $this->createQueryBuilder('fahrzeugdatenblatt')
			->andWhere('fahrzeugdatenblatt.fahrzeugMarke = :name')
			->setParameter('name',$markenname)
			->getQuery()
			->getOneOrNullResult();
	}

	/**
	 * @return mixed
	 */
	public function countAllCars()
	{
		$alleKarren = $this->createQueryBuilder('fahrzeugdatenblatt')
			->getQuery()
			->getArrayResult();
		$counted = count($alleKarren);
		return $counted;
	}

	/**
	 * @return mixed
	 */
	public function sortCarsAlphabetical()
	{
		$carsAlphabetical = $this->createQueryBuilder('fahrzeugdatenblatt')
							->orderBy('fahrzeugdatenblatt.fahrzeugMarke', 'ASC');
		return $carsAlphabetical;
	}

	/**
	 * @return mixed
	 */
	public function anfrageFilterCars($datum)
	{

		$transferdate = new \DateTime($datum);

		$cars = $this
			->createQueryBuilder('fahrzeugdatenblatt')
			->join('fahrzeugdatenblatt.transferfahrten', 'tf')
			->where('tf.createdAt = :date')
			->setParameter('date', $transferdate)
			->getQuery()
			->execute();

		/*$alleKarren = $this->createQueryBuilder('fahrzeugdatenblatt')
			->andWhere('fahrzeugdatenblatt.fahrzeugMarke = :name')
			->setParameter('name',$markenname)
			->getQuery()
			->execute(); */
		//counted = count($alleKarren);
		//dump($cars);die;
		return $cars;
	}
}
