<?php

namespace FahrzeugdatenblattBundle\Repository;

/**
 * TestkikiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestkikiRepository extends \Doctrine\ORM\EntityRepository
{
}
