<?php

namespace FahrzeugdatenblattBundle\Repository;

/**
 * FahrzeugdatenblattRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransferfahrtenRepository extends \Doctrine\ORM\EntityRepository
{

}


