<?php

namespace FahrzeugdatenblattBundle\Repository;

/**
 * VendorInformationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VendorInformationsRepository extends \Doctrine\ORM\EntityRepository
{
}
